apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutor-prod
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutor-prod
  template:
    metadata:
      labels:
        app: tutor-prod
    spec:
      containers:
        - name: app-dev
          image: zibas/poli-tutor-bot:a8a984569377eb92a3392c8d0e35122ace5a158d
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              cpu: "400m"
              memory: "1000Mi"
          ports:
            - containerPort: 5000
      volumes:
        - name: config
          secret:
            secretName: tutorapp-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tutor-prod-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 5000
  selector:
    app: tutor-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutorapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /tutorapp/$2
spec:
  tls:
    - hosts:
        - api.polinetwork.org
      secretName: tutor-prod-tls
  rules:
    - host: api.polinetwork.org
      http:
        paths:
          - path: /tutorapp(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: tutor-prod-service
                port:
                  number: 8000
